import assert from 'node:assert/strict';
import { describe, it } from 'node:test';

import {
  BlobRequestValidationError,
  parseInputPathname,
  parseOutputPathname,
  parseUploadClientPayload,
} from '../shared/blob-paths';

const uploadId = '123e4567-e89b-12d3-a456-426614174000';

describe('managed Vercel Blob path validation', () => {
  it('accepts the canonical input path generated by the backend', () => {
    const pathname = `otdr/input/2026/07/22/${uploadId}/batch.zip`;
    assert.deepEqual(parseInputPathname(pathname), {
      pathname,
      kind: 'input',
      uploadId,
      filename: 'batch.zip',
    });

    const filePathname =
      `otdr/input/2026/07/22/${uploadId}/000001-trace.sor`;
    assert.deepEqual(parseInputPathname(filePathname), {
      pathname: filePathname,
      kind: 'input',
      uploadId,
      filename: '000001-trace.sor',
    });
  });

  it('accepts only managed XLSX output paths', () => {
    const pathname = `otdr/output/2026/07/22/${uploadId}/FastReporter.xlsx`;
    assert.equal(parseOutputPathname(pathname).pathname, pathname);
    assert.throws(
      () => parseOutputPathname(pathname.replace('.xlsx', '.zip')),
      BlobRequestValidationError,
    );
  });

  it('rejects invalid dates, prefixes, UUID case, traversal, and filenames', () => {
    const invalidPaths = [
      `otdr/input/2026/02/30/${uploadId}/batch.zip`,
      `other/input/2026/07/22/${uploadId}/batch.zip`,
      `otdr/input/2026/07/22/${uploadId.toUpperCase()}/batch.zip`,
      `otdr/input/2026/07/22/${uploadId}/../batch.zip`,
      `otdr/input/2026/07/22/${uploadId}/other.zip`,
      `otdr/input/2026/07/22/${uploadId}/trace.sor`,
      `otdr/input/2026/07/22/${uploadId}/000001-document.pdf`,
    ];

    for (const pathname of invalidPaths) {
      assert.throws(() => parseInputPathname(pathname), BlobRequestValidationError);
    }
  });
});

describe('client upload payload validation', () => {
  it('returns the upload id from the expected payload', () => {
    assert.equal(
      parseUploadClientPayload(JSON.stringify({ uploadId })),
      uploadId,
    );
  });

  it('rejects missing, malformed, or non-string upload ids', () => {
    for (const payload of [null, '', '{}', '{', '{"uploadId": 1}']) {
      assert.throws(
        () => parseUploadClientPayload(payload),
        BlobRequestValidationError,
      );
    }
  });
});
